export const generalHardSkills: string[] = [
	"Data Analysis",
	"Financial Modeling",
	"Accounting",
	"Project Management",
	"Statistical Analysis",
	"Graphic Design",
	"Video Editing",
	"Photography",
	"CAD Design",
	"3D Modeling",
	"Mechanical Engineering",
	"Electrical Engineering",
	"Civil Engineering",
	"Architectural Design",
	"Medical Diagnostics",
	"Laboratory Techniques",
	"Legal Research",
	"Contract Drafting",
	"Translation",
	"Copywriting",
	"Content Creation",
	"SEO Optimization",
	"Digital Marketing",
	"Social Media Management",
	"Sales Techniques",
	"Customer Relationship Management",
	"Supply Chain Management",
	"Logistics Planning",
	"Quality Control",
	"Manufacturing Processes",
	"Teaching Methods",
	"Curriculum Development",
	"Public Speaking",
	"Event Planning",
	"Carpentry",
	"Welding",
	"Plumbing",
	"Automotive Repair",
	"Culinary Arts",
	"Fashion Design",
	"Music Production",
	"Audio Engineering",
	"Agriculture Techniques",
	"HVAC Systems",
	"Pharmaceutical Knowledge",
	"Nursing Skills",
	"First Aid",
	"Psychology Counseling",
	"Market Research",
];

export const itHardSkills: string[] = [
	"JavaScript",
	"TypeScript",
	"Python",
	"Java",
	"C++",
	"C#",
	"Ruby",
	"Go",
	"Rust",
	"Swift",
	"Kotlin",
	"PHP",
	"HTML5",
	"CSS3",
	"SASS/SCSS",
	"React",
	"Angular",
	"Vue.js",
	"Next.js",
	"Node.js",
	"Express.js",
	"Django",
	"Flask",
	"Spring Boot",
	"Ruby on Rails",
	"Laravel",
	"ASP.NET",
	"RESTful API Design",
	"GraphQL",
	"WebSockets",
	"Database Design",
	"SQL",
	"PostgreSQL",
	"MySQL",
	"MongoDB",
	"Redis",
	"Firebase",
	"Docker",
	"Kubernetes",
	"AWS",
	"Azure",
	"Google Cloud",
	"Terraform",
	"CI/CD Pipelines",
	"Git",
	"Linux Administration",
	"Shell Scripting",
	"Algorithm Design",
	"Data Structures",
	"Machine Learning",
	"Deep Learning",
	"Computer Vision",
	"Natural Language Processing",
	"Blockchain Development",
	"Smart Contracts",
	"Cybersecurity",
	"Penetration Testing",
	"Network Security",
	"UI/UX Design",
	"Figma",
	"Adobe XD",
	"Agile Methodologies",
	"Scrum",
	"DevOps Practices",
	"Microservices Architecture",
	"Test-Driven Development",
	"Unit Testing",
	"Integration Testing",
	"Mobile Development",
	"Game Development",
	"AR/VR Development",
	"Embedded Systems",
	"IoT Development",
	"Big Data",
	"Hadoop",
	"Spark",
	"Data Visualization",
	"Tableau",
	"Power BI",
];

export type HardSkill =
	| (typeof generalHardSkills)[number]
	| (typeof itHardSkills)[number];

export const generalHardSkillsRU: string[] = [
	"Анализ данных",
	"Финансовое моделирование",
	"Бухгалтерский учет",
	"Управление проектами",
	"Статистический анализ",
	"Графический дизайн",
	"Видеомонтаж",
	"Фотография",
	"CAD-дизайн",
	"3D-моделирование",
	"Машиностроение",
	"Электротехника",
	"Гражданское строительство",
	"Архитектурный дизайн",
	"Медицинская диагностика",
	"Лабораторные методы",
	"Юридические исследования",
	"Составление договоров",
	"Перевод",
	"Копирайтинг",
	"Создание контента",
	"SEO-оптимизация",
	"Цифровой маркетинг",
	"Управление соцсетями",
	"Техники продаж",
	"Управление клиентскими отношениями",
	"Управление цепочками поставок",
	"Планирование логистики",
	"Контроль качества",
	"Производственные процессы",
	"Методики преподавания",
	"Разработка учебных программ",
	"Публичные выступления",
	"Организация мероприятий",
	"Плотницкое дело",
	"Сварка",
	"Сантехника",
	"Ремонт автомобилей",
	"Кулинарное искусство",
	"Дизайн одежды",
	"Музыкальное производство",
	"Звукорежиссура",
	"Сельскохозяйственные технологии",
	"Системы HVAC",
	"Фармацевтические знания",
	"Медсестринские навыки",
	"Первая помощь",
	"Психологическое консультирование",
	"Маркетинговые исследования",
];

export const itHardSkillsRU: string[] = [
	"JavaScript",
	"TypeScript",
	"Python",
	"Java",
	"C++",
	"C#",
	"Ruby",
	"Go",
	"Rust",
	"Swift",
	"Kotlin",
	"PHP",
	"HTML5",
	"CSS3",
	"SASS/SCSS",
	"React",
	"Angular",
	"Vue.js",
	"Next.js",
	"Node.js",
	"Express.js",
	"Django",
	"Flask",
	"Spring Boot",
	"Ruby on Rails",
	"Laravel",
	"ASP.NET",
	"RESTful API Design",
	"GraphQL",
	"WebSockets",
	"Проектирование баз данных",
	"SQL",
	"PostgreSQL",
	"MySQL",
	"MongoDB",
	"Redis",
	"Firebase",
	"Docker",
	"Kubernetes",
	"AWS",
	"Azure",
	"Google Cloud",
	"Terraform",
	"CI/CD Pipelines",
	"Git",
	"Администрирование Linux",
	"Скриптинг в shell",
	"Проектирование алгоритмов",
	"Структуры данных",
	"Машинное обучение",
	"Глубокое обучение",
	"Компьютерное зрение",
	"Обработка естественного языка",
	"Разработка блокчейна",
	"Смарт-контракты",
	"Кибербезопасность",
	"Тестирование на проникновение",
	"Сетевая безопасность",
	"UI/UX дизайн",
	"Figma",
	"Adobe XD",
	"Гибкие методологии",
	"Scrum",
	"DevOps практики",
	"Микросервисная архитектура",
	"Разработка через тестирование",
	"Модульное тестирование",
	"Интеграционное тестирование",
	"Мобильная разработка",
	"Разработка игр",
	"AR/VR разработка",
	"Встраиваемые системы",
	"Разработка IoT",
	"Большие данные",
	"Hadoop",
	"Spark",
	"Визуализация данных",
	"Tableau",
	"Power BI",
];

export type HardSkillRU =
	| (typeof generalHardSkillsRU)[number]
	| (typeof itHardSkillsRU)[number];
