export const professions: string[] = [
	"Frontend Developer",
	"Backend Developer",
	"Full-Stack Developer",
	"Software Engineer",
	"Web Developer",
	"Mobile Developer",
	"Android Developer",
	"iOS Developer",
	"Java Developer",
	"Python Developer",
	"JavaScript Developer",
	"TypeScript Developer",
	"C++ Developer",
	"C# Developer",
	".NET Developer",
	"PHP Developer",
	"Go Developer",
	"Rust Developer",
	"Ruby Developer",
	"Kotlin Developer",
	"Swift Developer",
	"Flutter Developer",
	"React Developer",
	"Angular Developer",
	"Vue.js Developer",
	"Node.js Developer",
	"Django Developer",
	"Laravel Developer",
	"Spring Developer",
	"Game Developer",
	"Unity Developer",
	"Unreal Engine Developer",
	"Embedded Systems Developer",
	"Firmware Engineer",
	"DevOps Engineer",
	"Cloud Engineer",
	"AWS Engineer",
	"Azure Engineer",
	"Google Cloud Engineer",
	"Site Reliability Engineer (SRE)",
	"Data Engineer",
	"Big Data Engineer",
	"Machine Learning Engineer",
	"AI Engineer",
	"Computer Vision Engineer",
	"NLP Engineer",
	"Blockchain Developer",
	"Solidity Developer",
	"Smart Contract Developer",
	"Cybersecurity Engineer",
	"Penetration Tester",
	"Ethical Hacker",
	"Security Analyst",
	"Network Engineer",
	"Systems Administrator",
	"Database Administrator (DBA)",
	"SQL Developer",
	"NoSQL Developer",
	"Data Scientist",
	"Data Analyst",
	"Business Intelligence Analyst",
	"QA Engineer",
	"Test Automation Engineer",
	"UI/UX Designer",
	"Product Designer",
	"Graphic Designer",
	"Game Designer",
	"Technical Writer",
	"Scrum Master",
	"Agile Coach",
	"Product Manager (IT)",
	"Project Manager (IT)",
	"CTO (Chief Technology Officer)",
	"CIO (Chief Information Officer)",
	"IT Consultant",
	"Solution Architect",
	"Enterprise Architect",
	"Technical Support Engineer",
	"Help Desk Technician",
	"IT Recruiter",
	"ERP Developer",
	"SAP Consultant",
	"WordPress Developer",
	"Shopify Developer",
	"Low-Code Developer",
	"RPA Developer (Robotic Process Automation)",

	// ===== Business & Finance =====
	"Accountant",
	"Financial Analyst",
	"Investment Banker",
	"Auditor",
	"Tax Consultant",
	"Economist",
	"Actuary",
	"Risk Manager",
	"Stock Broker",
	"Hedge Fund Manager",
	"Business Analyst",
	"Management Consultant",
	"Entrepreneur",
	"Startup Founder",
	"Venture Capitalist",
	"HR Manager",
	"Recruiter",
	"Sales Manager",
	"Marketing Manager",
	"Digital Marketer",
	"SEO Specialist",
	"PPC Specialist",
	"Social Media Manager",
	"Content Marketer",
	"Brand Manager",
	"PR Manager",
	"Logistics Manager",
	"Supply Chain Manager",
	"Operations Manager",
	"Project Manager",
	"Product Manager",
	"Customer Support Specialist",
	"Real Estate Agent",
	"Insurance Agent",
	"Banker",
	"Loan Officer",
	"Credit Analyst",
	"Compliance Officer",
	"Data Entry Clerk",
	"Executive Assistant",
	"Office Manager",

	// ===== Healthcare & Medicine =====
	"Doctor",
	"Surgeon",
	"Cardiologist",
	"Neurologist",
	"Psychiatrist",
	"Pediatrician",
	"Dentist",
	"Orthodontist",
	"Pharmacist",
	"Nurse",
	"Paramedic",
	"Physiotherapist",
	"Radiologist",
	"Anesthesiologist",
	"Dermatologist",
	"Oncologist",
	"Veterinarian",
	"Medical Lab Technician",
	"Dietitian",
	"Optometrist",
	"Chiropractor",
	"Psychologist",
	"Therapist",
	"Speech Therapist",
	"Midwife",
	"Medical Researcher",
	"Biotechnologist",
	"Epidemiologist",
	"Genetic Counselor",
	"Forensic Pathologist",

	// ===== Engineering & Construction =====
	"Civil Engineer",
	"Mechanical Engineer",
	"Electrical Engineer",
	"Aerospace Engineer",
	"Chemical Engineer",
	"Biomedical Engineer",
	"Nuclear Engineer",
	"Environmental Engineer",
	"Robotics Engineer",
	"Automotive Engineer",
	"Petroleum Engineer",
	"Marine Engineer",
	"Structural Engineer",
	"Architect",
	"Urban Planner",
	"Construction Manager",
	"Surveyor",
	"Welder",
	"Electrician",
	"Plumber",
	"Carpenter",
	"Mason",
	"HVAC Technician",
	"Civil Technician",
	"CAD Designer",
	"Industrial Designer",
	"Quality Control Engineer",
	"Mining Engineer",
	"Geotechnical Engineer",
	"Fire Protection Engineer",

	// ===== Creative & Media =====
	"Graphic Designer",
	"Illustrator",
	"Animator",
	"Video Editor",
	"Photographer",
	"Filmmaker",
	"Screenwriter",
	"Journalist",
	"Editor",
	"Copywriter",
	"Content Creator",
	"Blogger",
	"Podcaster",
	"Musician",
	"Singer",
	"Actor",
	"Director",
	"Producer",
	"Sound Engineer",
	"Game Designer",
	"3D Artist",
	"Fashion Designer",
	"Interior Designer",
	"Art Director",
	"Creative Director",
	"UX Writer",
	"Motion Designer",
	"Voice Actor",
	"Composer",
	"Choreographer",

	// ===== Science & Research =====
	"Biologist",
	"Chemist",
	"Physicist",
	"Astronomer",
	"Geologist",
	"Meteorologist",
	"Archaeologist",
	"Paleontologist",
	"Oceanographer",
	"Zoologist",
	"Botanist",
	"Microbiologist",
	"Geneticist",
	"Neuroscientist",
	"Materials Scientist",
	"Quantum Physicist",
	"Data Scientist",
	"Statistician",
	"Mathematician",
	"Researcher",
	"Climate Scientist",
	"AI Researcher",
	"Space Scientist",
	"Nanotechnologist",
	"Forensic Scientist",

	// ===== Education & Teaching =====
	"University Professor",
	"High School Teacher",
	"Elementary Teacher",
	"Math Teacher",
	"Science Teacher",
	"History Teacher",
	"English Teacher",
	"Language Teacher",
	"Music Teacher",
	"Art Teacher",
	"Physical Education Teacher",
	"Special Education Teacher",
	"Tutor",
	"Librarian",
	"School Counselor",
	"ESL Teacher",
	"Early Childhood Educator",
	"College Dean",
	"Education Consultant",
	"Instructional Designer",

	// ===== Legal & Government =====
	"Lawyer",
	"Judge",
	"Paralegal",
	"Prosecutor",
	"Public Defender",
	"Corporate Lawyer",
	"Patent Attorney",
	"Immigration Lawyer",
	"Notary",
	"Politician",
	"Diplomat",
	"Police Officer",
	"Detective",
	"FBI Agent",
	"CIA Analyst",
	"Forensic Analyst",
	"Customs Officer",
	"Firefighter",
	"Military Officer",
	"Intelligence Officer",

	// ===== Trades & Services =====
	"Chef",
	"Baker",
	"Bartender",
	"Barista",
	"Waiter",
	"Hotel Manager",
	"Travel Agent",
	"Flight Attendant",
	"Pilot",
	"Air Traffic Controller",
	"Taxi Driver",
	"Truck Driver",
	"Bus Driver",
	"Train Conductor",
	"Ship Captain",
	"Hairdresser",
	"Makeup Artist",
	"Massage Therapist",
	"Personal Trainer",
	"Lifeguard",
	"Security Guard",
	"Janitor",
	"Housekeeper",
	"Landscaper",
	"Gardener",
	"Farmer",
	"Fisherman",
	"Butcher",
	"Tailor",
	"Jeweler",

	// ===== Miscellaneous =====
	"Astronaut",
	"Ethical Hacker",
	"Cryptographer",
	"Ethnographer",
	"Sommelier",
	"Arborist",
	"Beekeeper",
	"Cartoonist",
	"Locksmith",
	"Watchmaker",
	"Blacksmith",
	"Glassblower",
	"Funeral Director",
	"Venture Scout",
	"Cryptocurrency Trader",
	"Drone Operator",
	"Yoga Instructor",
	"Meditation Coach",
	"Life Coach",
	"Career Counselor",
	"Event Planner",
	"Wedding Planner",
	"Fitness Instructor",
	"Park Ranger",
	"Zookeeper",
	"Animal Trainer",
	"Forester",
	"Archaeological Surveyor",
	"Gemologist",
	"Horologist",
];

export type Profession = (typeof professions)[number];

export const professionsRU: string[] = [
	// ===== IT =====
	"Фронтенд-разработчик",
	"Бэкенд-разработчик",
	"Фулл-стек разработчик",
	"Инженер-программист",
	"Веб-разработчик",
	"Мобильный разработчик",
	"Android-разработчик",
	"iOS-разработчик",
	"Java-разработчик",
	"Python-разработчик",
	"JavaScript-разработчик",
	"TypeScript-разработчик",
	"C++ разработчик",
	"C# разработчик",
	".NET разработчик",
	"PHP разработчик",
	"Go разработчик",
	"Rust разработчик",
	"Ruby разработчик",
	"Kotlin разработчик",
	"Swift разработчик",
	"Flutter разработчик",
	"React разработчик",
	"Angular разработчик",
	"Vue.js разработчик",
	"Node.js разработчик",
	"Django разработчик",
	"Laravel разработчик",
	"Spring разработчик",
	"Разработчик игр",
	"Unity разработчик",
	"Unreal Engine разработчик",
	"Разработчик встраиваемых систем",
	"Инженер микропрограмм",
	"DevOps инженер",
	"Облачный инженер",
	"AWS инженер",
	"Azure инженер",
	"Google Cloud инженер",
	"Инженер надежности сайтов (SRE)",
	"Инженер данных",
	"Big Data инженер",
	"Инженер машинного обучения",
	"ИИ-инженер",
	"Инженер компьютерного зрения",
	"Инженер NLP",
	"Блокчейн-разработчик",
	"Solidity разработчик",
	"Разработчик смарт-контрактов",
	"Инженер кибербезопасности",
	"Тестировщик на проникновение",
	"Этичный хакер",
	"Аналитик безопасности",
	"Сетевой инженер",
	"Системный администратор",
	"Администратор БД (DBA)",
	"SQL разработчик",
	"NoSQL разработчик",
	"Дата-сайентист",
	"Аналитик данных",
	"Аналитик бизнес-аналитики",
	"QA инженер",
	"Инженер автоматизированного тестирования",
	"UI/UX дизайнер",
	"Продуктовый дизайнер",
	"Графический дизайнер",
	"Гейм-дизайнер",
	"Технический писатель",
	"Scrum-мастер",
	"Agile-коуч",
	"Продуктовый менеджер (IT)",
	"Менеджер проектов (IT)",
	"CTO (Технический директор)",
	"CIO (Директор по информационным технологиям)",
	"IT-консультант",
	"Архитектор решений",
	"Корпоративный архитектор",
	"Инженер технической поддержки",
	"Специалист службы поддержки",
	"IT-рекрутер",
	"ERP разработчик",
	"SAP консультант",
	"WordPress разработчик",
	"Shopify разработчик",
	"Low-Code разработчик",
	"RPA разработчик",

	// ===== Бизнес и финансы =====
	"Бухгалтер",
	"Финансовый аналитик",
	"Инвестиционный банкир",
	"Аудитор",
	"Налоговый консультант",
	"Экономист",
	"Актуарий",
	"Менеджер по рискам",
	"Биржевой брокер",
	"Управляющий хедж-фондом",
	"Бизнес-аналитик",
	"Управленческий консультант",
	"Предприниматель",
	"Основатель стартапа",
	"Венчурный капиталист",
	"HR-менеджер",
	"Рекрутер",
	"Менеджер по продажам",
	"Маркетинг-менеджер",
	"Цифровой маркетолог",
	"SEO-специалист",
	"PPC-специалист",
	"Менеджер соцсетей",
	"Контент-маркетолог",
	"Бренд-менеджер",
	"PR-менеджер",
	"Логистический менеджер",
	"Менеджер цепочки поставок",
	"Операционный менеджер",
	"Менеджер проектов",
	"Продуктовый менеджер",
	"Специалист поддержки клиентов",
	"Агент по недвижимости",
	"Страховой агент",
	"Банкир",
	"Кредитный специалист",
	"Кредитный аналитик",
	"Специалист по комплаенсу",
	"Оператор ввода данных",
	"Исполнительный помощник",
	"Офис-менеджер",

	// ===== Здравоохранение и медицина =====
	"Врач",
	"Хирург",
	"Кардиолог",
	"Невролог",
	"Психиатр",
	"Педиатр",
	"Стоматолог",
	"Ортодонт",
	"Фармацевт",
	"Медсестра",
	"Парамедик",
	"Физиотерапевт",
	"Рентгенолог",
	"Анестезиолог",
	"Дерматолог",
	"Онколог",
	"Ветеринар",
	"Лаборант",
	"Диетолог",
	"Офтальмолог",
	"Хиропрактик",
	"Психолог",
	"Терапевт",
	"Логопед",
	"Акушерка",
	"Медицинский исследователь",
	"Биотехнолог",
	"Эпидемиолог",
	"Генетический консультант",
	"Судебный патологоанатом",

	// ===== Инженерия и строительство =====
	"Инженер-строитель",
	"Инженер-механик",
	"Инженер-электрик",
	"Авиакосмический инженер",
	"Химический инженер",
	"Биомедицинский инженер",
	"Ядерный инженер",
	"Инженер-эколог",
	"Инженер-робототехник",
	"Автомобильный инженер",
	"Нефтяной инженер",
	"Морской инженер",
	"Инженер-конструктор",
	"Архитектор",
	"Градостроитель",
	"Менеджер строительства",
	"Геодезист",
	"Сварщик",
	"Электрик",
	"Сантехник",
	"Плотник",
	"Каменщик",
	"Техник HVAC",
	"Техник-строитель",
	"CAD-дизайнер",
	"Промышленный дизайнер",
	"Инженер по контролю качества",
	"Горный инженер",
	"Геотехнический инженер",
	"Инженер противопожарной защиты",

	// ===== Творчество и медиа =====
	"Графический дизайнер",
	"Иллюстратор",
	"Аниматор",
	"Видеомонтажер",
	"Фотограф",
	"Кинорежиссер",
	"Сценарист",
	"Журналист",
	"Редактор",
	"Копирайтер",
	"Создатель контента",
	"Блогер",
	"Подкастер",
	"Музыкант",
	"Певец",
	"Актер",
	"Режиссер",
	"Продюсер",
	"Звукорежиссер",
	"Гейм-дизайнер",
	"3D-художник",
	"Дизайнер одежды",
	"Дизайнер интерьеров",
	"Арт-директор",
	"Креативный директор",
	"UX-писатель",
	"Моушн-дизайнер",
	"Актер озвучки",
	"Композитор",
	"Хореограф",

	// ===== Наука и исследования =====
	"Биолог",
	"Химик",
	"Физик",
	"Астроном",
	"Геолог",
	"Метеоролог",
	"Археолог",
	"Палеонтолог",
	"Океанограф",
	"Зоолог",
	"Ботаник",
	"Микробиолог",
	"Генетик",
	"Нейробиолог",
	"Материаловед",
	"Квантовый физик",
	"Дата-сайентист",
	"Статистик",
	"Математик",
	"Исследователь",
	"Климатолог",
	"Исследователь ИИ",
	"Космический ученый",
	"Нанотехнолог",
	"Криминалист",

	// ===== Образование и преподавание =====
	"Профессор университета",
	"Учитель старших классов",
	"Учитель начальных классов",
	"Учитель математики",
	"Учитель естественных наук",
	"Учитель истории",
	"Учитель английского",
	"Преподаватель языков",
	"Учитель музыки",
	"Учитель рисования",
	"Учитель физкультуры",
	"Учитель специального образования",
	"Репетитор",
	"Библиотекарь",
	"Школьный психолог",
	"Преподаватель ESL",
	"Воспитатель",
	"Декан",
	"Консультант по образованию",
	"Дизайнер учебных программ",

	// ===== Юриспруденция и госуправление =====
	"Юрист",
	"Судья",
	"Помощник юриста",
	"Прокурор",
	"Государственный защитник",
	"Корпоративный юрист",
	"Патентный поверенный",
	"Иммиграционный юрист",
	"Нотариус",
	"Политик",
	"Дипломат",
	"Полицейский",
	"Детектив",
	"Агент ФБР",
	"Аналитик ЦРУ",
	"Криминалист",
	"Таможенник",
	"Пожарный",
	"Офицер",
	"Офицер разведки",

	// ===== Торговля и услуги =====
	"Шеф-повар",
	"Пекарь",
	"Бармен",
	"Бариста",
	"Официант",
	"Менеджер отеля",
	"Турагент",
	"Стюардесса",
	"Пилот",
	"Авиадиспетчер",
	"Таксист",
	"Дальнобойщик",
	"Водитель автобуса",
	"Проводник",
	"Капитан судна",
	"Парикмахер",
	"Визажист",
	"Массажист",
	"Персональный тренер",
	"Спасатель",
	"Охранник",
	"Уборщик",
	"Горничная",
	"Ландшафтный дизайнер",
	"Садовник",
	"Фермер",
	"Рыбак",
	"Мясник",
	"Портной",
	"Ювелир",

	// ===== Разное =====
	"Космонавт",
	"Этичный хакер",
	"Криптограф",
	"Этнограф",
	"Сомелье",
	"Арборист",
	"Пчеловод",
	"Карикатурист",
	"Слесарь",
	"Часовщик",
	"Кузнец",
	"Стеклодув",
	"Похоронный агент",
	"Скаут венчурных проектов",
	"Трейдер криптовалют",
	"Оператор дронов",
	"Инструктор йоги",
	"Тренер по медитации",
	"Лайф-коуч",
	"Карьерный консультант",
	"Организатор мероприятий",
	"Организатор свадеб",
	"Фитнес-инструктор",
	"Лесник",
	"Смотритель зоопарка",
	"Дрессировщик",
	"Лесничий",
	"Археолог-геодезист",
	"Геммолог",
	"Хоролог",
];

export type ProfessionRU = (typeof professionsRU)[number];

export const getProfessionsByLanguage = (language: string): string[] => {
	return language === "en" ? professions : professionsRU;
};
