export const softSkills: string[] = [
	"Communication",
	"Teamwork",
	"Problem-solving",
	"Critical thinking",
	"Adaptability",
	"Time management",
	"Leadership",
	"Creativity",
	"Emotional intelligence",
	"Conflict resolution",
	"Decision making",
	"Stress management",
	"Active listening",
	"Collaboration",
	"Negotiation",
	"Persuasion",
	"Public speaking",
	"Networking",
	"Empathy",
	"Patience",
	"Resilience",
	"Self-motivation",
	"Work ethic",
	"Attention to detail",
	"Organization",
	"Flexibility",
	"Cultural awareness",
	"Accepting feedback",
	"Delegation",
	"Mentoring",
	"Presentation skills",
	"Storytelling",
	"Diplomacy",
	"Mediation",
	"Strategic thinking",
	"Innovation",
	"Resourcefulness",
	"Self-awareness",
	"Self-regulation",
	"Motivation",
	"Social skills",
	"Interpersonal skills",
	"Positive attitude",
	"Open-mindedness",
	"Reliability",
	"Accountability",
	"Initiative",
	"Professionalism",
	"Dependability",
	"Tactfulness",
];

export const softSkillsRU: string[] = [
	"Коммуникация",
	"Командная работа",
	"Решение проблем",
	"Критическое мышление",
	"Адаптивность",
	"Тайм-менеджмент",
	"Лидерство",
	"Креативность",
	"Эмоциональный интеллект",
	"Разрешение конфликтов",
	"Принятие решений",
	"Управление стрессом",
	"Активное слушание",
	"Коллаборация",
	"Переговоры",
	"Убеждение",
	"Публичные выступления",
	"Нетворкинг",
	"Эмпатия",
	"Терпение",
	"Устойчивость",
	"Самомотивация",
	"Рабочая этика",
	"Внимание к деталям",
	"Организованность",
	"Гибкость",
	"Культурная осведомленность",
	"Принятие обратной связи",
	"Делегирование",
	"Наставничество",
	"Навыки презентации",
	"Сторителлинг",
	"Дипломатия",
	"Посредничество",
	"Стратегическое мышление",
	"Инновационность",
	"Ресурсность",
	"Самосознание",
	"Саморегуляция",
	"Мотивация",
	"Социальные навыки",
	"Межличностные навыки",
	"Позитивный настрой",
	"Открытость",
	"Надежность",
	"Ответственность",
	"Инициативность",
	"Профессионализм",
	"Надежность",
	"Тактичность",
];
